---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name:   twi-ttd-site-generator-cronjob
spec:
  schedule: "50 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name:  twi-ttd-site-generator-cronjob-container
              image: gcr.io/bootiful/twi-ttd-site-generator:latest
              imagePullPolicy: Always
              envFrom:
                - configMapRef:
                    name: ttd-twi-site-generator-config
                - configMapRef:
                    name: ttd-twi-configmap
          restartPolicy: OnFailure